#!/usr/bin/ruby

# fasta-to-mcl-to-spreadsheet  Run MCL and show which species clusters contain
# Copyright (C) 2011 Aleksandr Levchuk; Hagop Atamian
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

DIR = File.dirname(__FILE__)

if ARGV.size < 2
  STDERR.puts "Usage: #{__FILE__.split('/').last} <sourcefasta> <idsfile1> [<idsfile2> ...]"
  exit(1)
end

SOURCE_FASTA = ARGV[0]
ID_FILES     = ARGV[1..-1]

File.open("progress.log", 'a') {} # Clear log file

ID_FILES.each do |ids_file|

  ids = File.open(ids_file){|f| f.readlines}.collect{|i| i.chomp}

  File.open("progress.log", 'a') do |progress|
    progress.puts
    progress.puts ids.inspect
    progress.puts "Writing #{ids_file}.fasta ..."
  end

  File.open("#{ids_file}.fasta", 'w') do |out|
    File.open(SOURCE_FASTA) do |s|
      print_sequence = false
      while line = s.gets
        if line =~ /^>(.*?)( |\n)/
          print_sequence = false
          if ids.include?($1)

            ids.delete($1) # Forget assession IDs as soon as
                               # they are encountered. Saves time.

            print_sequence = true
            out.puts line.chomp
          end

        elsif print_sequence
          out.puts line.chomp 
        end
      end
    end
  end
end
