#!/bin/bash

# fasta-to-mcl-to-spreadsheet  Run MCL and show which species clusters contain
# Copyright (C) 2011 Aleksandr Levchuk; Hagop Atamian
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

source_fasta="24_Insect_SG_EST_sequences.fasta"

for i in results/*-ids; do
  echo ./003-ids-to-fasta $source_fasta $i
done
